name = "clubffxiv-registry"
main = "src/index.ts"
compatibility_date = "2024-09-01"

# Replace these IDs after running `wrangler kv:namespace create CLUBS_KV`
# and `wrangler kv:namespace create CLUBS_KV --preview`
[[kv_namespaces]]
binding = "CLUBS_KV"
id = "1d83f396874649f99e5ad338fbd44581"
preview_id = "b693f02a48714b798d8f43deb7b96b59"
