<Project Sdk="Dalamud.NET.Sdk/15.0.0">

	<PropertyGroup>
		<Authors>electr0sheep</Authors>
		<Description>Tune into in-game housing radio stations. Custom music for FFXIV clubs.</Description>
		<Version>0.1.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.3.0" />
	</ItemGroup>

</Project>
